SELECT 
    PL.PROGRAMMINGLANGUAGE,
    (SELECT T.TOOL FROM DIM_TOOL T 
     WHERE T.TOOL = 'GIT' AND EXISTS (
         SELECT 1 FROM BRIDGE_COURSE_TOOL BCT 
         WHERE BCT.TOOL_ID = T.ID AND FC.ID = BCT.COURSEID)) AS TOOL,
    (SELECT K.KNOWLEDGE FROM DIM_KNOWLEDGE K 
     WHERE K.KNOWLEDGE IN ('DATA ANALYSIS', 'DATA WAREHOUSE') AND EXISTS (
         SELECT 1 FROM BRIDGE_COURSE_KNOWLEDGE BCK 
         WHERE BCK.KNOWLEDGE_ID = K.ID AND FC.ID = BCK.COURSEID)) AS KNOWLEDGE,
    (SELECT FW.FRAMEWORK FROM DIM_FRAMEWORK FW 
     WHERE FW.FRAMEWORK IN ('SPRING', 'SPARK') AND EXISTS (
         SELECT 1 FROM BRIDGE_COURSE_FRAMEWORK BCF 
         WHERE BCF.FRAMEWORK_ID = FW.ID AND FC.ID = BCF.COURSEID)) AS FRAMEWORK,
    (SELECT PF.PLATFORM FROM DIM_PLATFORM PF 
     WHERE PF.PLATFORM IN ('AZURE', 'CLOUD', 'MYSQL') AND EXISTS (
         SELECT 1 FROM BRIDGE_COURSE_PLATFORM BCP 
         WHERE BCP.PLATFORM_ID = PF.ID AND FC.ID = BCP.COURSEID)) AS PLATFORM,
    COUNT(DISTINCT FC.ID) AS NumberOfCourse
FROM 
    FACT_COURSE FC
JOIN 
    DIM_COURSE C ON FC.COURSEID = C.ID
JOIN 
    BRIDGE_COURSE_PROGRAMMINGLANGUAGE BCPL ON FC.ID = BCPL.COURSEID
JOIN 
    DIM_PROGRAMMINGLANGUAGE PL ON BCPL.PROGRAMMINGLANGUAGE_ID = PL.ID 
    AND PL.PROGRAMMINGLANGUAGE IN ('JAVA', 'PYTHON')
GROUP BY 
    PL.PROGRAMMINGLANGUAGE
ORDER BY 
    NumberOfCourse DESC;